### ISSUE TITLE
if / else

### ISSUE THREAD

**Issue by dominiclooser** [pug-php/twig#1]
if / else seems not to work.

**Comment by kylekatarnls** [comment]
Indeed an `{% endif %}` is insterted before the `else`. I will see if we can do something without touching the Pug engine.

**Comment by dominiclooser** [comment]
great. thanks, mate!

**Comment by kylekatarnls** [comment]
Hi, you can retry with version 1.0.0.

**Comment by dominiclooser** [comment]
Just had the oportunity to test it on a new project. Works! Thanks
