### ISSUE TITLE
Doesn't work with include, block ?

### ISSUE THREAD

**Issue by dzpt** [pug-php/twig#5]
If the pug file includes other pug file, it will not be converted

`Fatal error: Uncaught Phug\CompilerException: Failed to compile: Source file footer not found Paths: Extensions: , .pug, .jade Line: 0 Offset:`

`block` will be removed also.

**Comment by kylekatarnls** [comment]
I can't investigate more this without code of a reproductible case.

`include` and `block` works as documented in https://phug-lang.com/ (which is also following pugjs specs).

You can see the examples here: https://github.com/pug-php/twig/pull/6/files#diff-c2316e424778002a0c3f959260116468a50d9d4a49f0704f47f3fcbec85677cd

I added unit tests in this project to ensure it's fully compatible with Twig compilation.

To sum-up, what you can do with `block` in a Pug template (either using pugjs, pug-php or twig compilation) is:
- anonymous block in mixin definition (take the inner content of the mixin call)
- named block (can be overridden when the a template `extends` this template that contains named block)
